// Bundles the three browser entry points into minified IIFE strings the Worker serves at runtime:
//   web/app.ts          -> VIEWER_JS      (inlined into the viewer page behind a CSP nonce)
//   push/bookmarklet.entry.ts -> BOOKMARKLET_JS (wrapped into a javascript: URL by /setup)
//   push/userscript.ts  -> USERSCRIPT_JS  (wrapped into the .user.js file by /setup)
// Output: worker/src/generated/assets.ts (git-ignored). The Worker makes no static-asset requests,
// so no public asset path reveals the deployment.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

async function bundle(entry) {
  const result = await build({
    entryPoints: [join(root, entry)],
    bundle: true,
    write: false,
    minify: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    charset: 'ascii', // no raw non-ASCII: safe inside javascript: URLs and any HTML context
    legalComments: 'none',
    logLevel: 'warning',
  });
  const text = result.outputFiles[0].text.trim();
  if (text.length === 0) throw new Error(`${entry}: empty bundle`);
  return text;
}

const [VIEWER_JS, BOOKMARKLET_JS, USERSCRIPT_JS] = await Promise.all([
  bundle('web/app.ts'),
  bundle('push/bookmarklet.entry.ts'),
  bundle('push/userscript.ts'),
]);

// A bookmarklet must be a single line.
if (/[\r\n]/.test(BOOKMARKLET_JS)) throw new Error('push/bookmarklet.entry.ts bundle contains a newline');

const out = join(root, 'worker', 'src', 'generated');
mkdirSync(out, { recursive: true });
const body =
  '// GENERATED by scripts/build.mjs. Do not edit; git-ignored.\n' +
  `export const VIEWER_JS = ${JSON.stringify(VIEWER_JS)};\n` +
  `export const BOOKMARKLET_JS = ${JSON.stringify(BOOKMARKLET_JS)};\n` +
  `export const USERSCRIPT_JS = ${JSON.stringify(USERSCRIPT_JS)};\n`;
writeFileSync(join(out, 'assets.ts'), body, 'utf8');

console.log(
  `built worker/src/generated/assets.ts (viewer ${VIEWER_JS.length} B, bookmarklet ${BOOKMARKLET_JS.length} B, userscript ${USERSCRIPT_JS.length} B)`,
);
